server:
  port: 7001

eureka:
  instance:
    hostname: 106.14.2.133  #服务端实例名称
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://106.14.2.133:7002/eureka/
