server:
  port: 8088

spring:
  application:
    name: order-feign-service

eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://106.14.2.133:7001/eureka/,http://106.14.2.133:7002/eureka/
  instance:
    instance-id: order-feign
    #访问路径可以显示IP地址
    prefer-ip-address: true
#设置feign客户端超时时间(OpenFeign默认支持ribbon)
ribbon:
  #指的是建立连接所用的时间，适用于网络状况正常的情况下,两端连接所用的时间
  ReadTimeout: 5000
  #指的是建立连接后从服务器读取到可用资源所用的时间
  ConnectTimeout: 5000

logging:
  level:
    com.atguigu.springcloud.service.OrderService: debug